import './globals.css';
import { Poppins } from 'next/font/google';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

const poppins = Poppins({
    weight: ['400', '700', '800', '900'],
    subsets: ['latin'],
});

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={`${poppins.className} overflow-hidden`}>
                {children}
            </body>
        </html>
    );
}
